language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules

addons:
  apt:
    packages:
      - git

install:
  - npm install -g codecov
  - npm install
  - ssh-keygen -P "" -t rsa -b 4096 -m PEM -f jwtRS256.pem
  - mkdir -p $TRAVIS_BUILD_DIR/test/data/testrepo
  - echo -e "JWT_PRIV_KEY_PATH=$TRAVIS_BUILD_DIR/test/data/jwtRS256.pem\nGPG_PRIV_PATH=$TRAVIS_BUILD_DIR/test/data/sudo-bot-test.priv\nGPG_PUB_PATH=$TRAVIS_BUILD_DIR/test/data/sudo-bot-test.pub\nGPG_PRIV_PASSWORD=fYWwRmbkcd3tXSqcCrjWBCFBhzEW6ASP98zcSH\nREPO=sudo-bot\nOWNER=sudo-bot\nINSTALLATION_ID=123456\nBOT_NAME=Bot\nBOT_EMAIL=sudo-bot@wdes.fr\nREPO_DIR=/home/sudo/myrepo" > .env

script:
  - npm run test
  - npm run report-coverage
  - codecov
