name: Run tests

on: [push]

jobs:
    test-node:
        name: Test on node ${{ matrix.node_version }}
        runs-on: ubuntu-latest
        container:
            image: node:${{ matrix.node_version }}-alpine
        strategy:
            matrix:
                node_version: ["10", "12"]

        steps:
            - uses: actions/checkout@v3
            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
            - uses: actions/cache@v3
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-
            - name: Install modules
              run: yarn install
            - name: Prepare files
              run: |
                  apk add --no-cache openssh-client git bash curl
                  ssh-keygen -P "" -t rsa -b 4096 -m PEM -f jwtRS256.pem
                  mkdir -p $PWD/test/data/testrepo
            - name: Run node tests
              run: |
                  yarn run test
                  yarn run report-coverage
            - name: Send coverage
              uses: codecov/codecov-action@v3
